[metadata]
name = proxy
url = https://storyboard.openstack.org/#!/project/openstack/aodh
summary = OpenStack Telemetry Alarming
description_file =
    README.rst
author = OpenStack
author_email = openstack-discuss@lists.openstack.org
home_page = https://docs.openstack.org/aodh/latest/
python_requires = >=3.9
classifier =
    Environment :: OpenStack
    Intended Audience :: Information Technology
    Intended Audience :: System Administrators
    License :: OSI Approved :: Apache Software License
    Operating System :: POSIX :: Linux
    Programming Language :: Python
    Programming Language :: Python :: Implementation :: CPython
    Programming Language :: Python :: 3 :: Only
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.9
    Programming Language :: Python :: 3.10
    Programming Language :: Python :: 3.11
    Programming Language :: Python :: 3.12
    Topic :: System :: Monitoring

[options]
packages =
    proxy

[extras]
mysql =
    SQLAlchemy-Utils>=0.41.0
    alembic>=0.7.2
    PyMySQL>=0.6.2 # MIT License

postgresql =
    SQLAlchemy-Utils>=0.41.0
    alembic>=0.7.2
    psycopg2>=2.9.6

zaqar =
    python-zaqarclient>=1.2.0

[entry_points]
wsgi_scripts =
    proxy-api = proxy.api.app:build_wsgi_app

oslo.config.opts =
    proxy = proxy.opts:list_opts
    proxy-auth = proxy.opts:list_keystoneauth_opts

oslo.config.opts.defaults =
    proxy = proxy.conf.defaults:set_lib_defaults

oslo.policy.policies =
    proxy = proxy.api.policies:list_rules

oslo.policy.enforcer =
    proxy = proxy.api.policies:get_enforcer
